%% Resolve the apparent dark-branch jump by fixed-sheet continuation
clear; clc;

rootDir=fileparts(mfilename('fullpath'));
dataDir=fullfile(rootDir,'results','full_complex_band_180k');
S=load(fullfile(rootDir,'results', ...
    'StrictRayleighBIC_180kHz_7p10deg_final.mat'));
cfg=S.cfg; cfg.N=89; cfg.K=11; cfg.solve_scattering=false;

% The lower broad pole reaches the vertical n=0 branch cut near kappa=.422.
kappaN0=[.42:.001:.50];
n0=ni2019_continue_pole_fixed_sheet(cfg,kappaN0, ...
    complex(.421456741233674,.124949985350905),0, ...
    'OuterIterations',12,'Display','off');

% The upper broad pole reaches the vertical n=-1 branch cut near kappa=.424.
kappaNm1=[.43:-.002:.002,0];
nm1=ni2019_continue_pole_fixed_sheet(cfg,kappaNm1, ...
    complex(.577473243272,.205039205144),-1, ...
    'OuterIterations',12,'Display','off');

n0Table=track_table(n0);
nm1Table=track_table(nm1);
writetable(n0Table,fullfile(dataDir,'dark_branch_n0_fixed_sheet.csv'));
writetable(nm1Table,fullfile(dataDir,'dark_branch_nm1_fixed_sheet.csv'));
save(fullfile(dataDir,'dark_branch_fixed_sheet_audit.mat'), ...
    'n0','nm1','n0Table','nm1Table','cfg','-v7.3');

fprintf('n=0 continuation: max sigma %.3e, min overlap %.8f\n', ...
    max(n0.sigma_ratio),min(n0.mode_overlap(2:end)));
fprintf('n=-1 continuation: max sigma %.3e, min overlap %.8f\n', ...
    max(nm1.sigma_ratio),min(nm1.mode_overlap(2:end)));

function T=track_table(track)
T=table(track.kappa(:),real(track.Omega(:)),imag(track.Omega(:)), ...
    track.Q(:),real(track.q(:)),imag(track.q(:)), ...
    track.sigma_ratio(:),track.residual(:),track.mode_overlap(:), ...
    repmat(track.target_order,numel(track.kappa),1), ...
    'VariableNames',{'kappa','Omega_real','Omega_imag','Q', ...
    'q_real','q_imag','sigma_ratio','residual','mode_overlap', ...
    'fixed_order'});
end
