function pole=ni2019_find_isolated_groove_cluster_pole( ...
    widths,depths,gaps,K,cWater,fSeed,varargin)
%NI2019_FIND_ISOLATED_GROOVE_CLUSTER_POLE Refine one cluster QNM pole.
p=inputParser;
addParameter(p,'OuterIterations',9); addParameter(p,'Display','off');
addParameter(p,'SMax',max(300,(K+12)*pi));
addParameter(p,'PanelsPerPi',4);
parse(p,varargin{:}); opt=p.Results;
f=fSeed; history=complex(nan(opt.OuterIterations+1,1)); history(1)=f;
sigmaHistory=nan(opt.OuterIterations+1,1); exitflag=nan;
for outer=1:opt.OuterIterations
    op0=operator_at(f); rowScale=op0.row_scale(:);
    columnScale=op0.column_scale(:).'; F0=op0.F./rowScale./columnScale;
    [U,S,V]=svd(F0,'econ'); sv=diag(S); u=U(:,end); v=V(:,end);
    sigmaHistory(outer)=sv(end)/max(sv(1),eps);
    options=optimoptions('fsolve','Display',opt.Display, ...
        'FunctionTolerance',1e-11,'StepTolerance',1e-11, ...
        'OptimalityTolerance',1e-11,'MaxFunctionEvaluations',80, ...
        'MaxIterations',40);
    [x,~,exitflag]=fsolve(@projected_equation, ...
        [real(f),imag(f)]/1e3,options);
    fNew=(x(1)+1i*x(2))*1e3; history(outer+1)=fNew;
    if abs(fNew-f)<=1e-10*max(abs(fNew),1), f=fNew; break; end
    f=fNew;
end
op=operator_at(f); [~,S,V]=svd(op.Fscaled,'econ'); sv=diag(S);
vScaled=V(:,end); Cscaled=vScaled./transpose(op.column_scale);
Cphysical=Cscaled./op.vertical_scale;
CbyGroove=reshape(Cphysical,K,op.L);
surface=Cscaled.*op.cos_depth_normalized;
surfaceByGroove=reshape(surface,K,op.L);
grooveFraction=sum(abs(CbyGroove).^2,1); grooveFraction= ...
    grooveFraction/max(sum(grooveFraction),eps);
surfaceGrooveFraction=sum(abs(surfaceByGroove).^2,1); ...
    surfaceGrooveFraction=surfaceGrooveFraction/ ...
    max(sum(surfaceGrooveFraction),eps);
pole=struct('frequency_hz',f,'Q',real(f)/(2*imag(f)), ...
    'sigma_ratio',sv(end)/max(sv(1),eps), ...
    'raw_residual',norm(op.F*Cscaled)/max(norm(Cscaled),eps), ...
    'exitflag',exitflag,'history_hz',history(isfinite(history)), ...
    'sigma_history',sigmaHistory(isfinite(sigmaHistory)), ...
    'operator',op,'C_scaled',Cscaled,'C_physical',Cphysical, ...
    'C_by_groove',CbyGroove,'surface_pressure_by_groove', ...
    surfaceByGroove,'groove_fraction',grooveFraction, ...
    'surface_groove_fraction',surfaceGrooveFraction);

    function opLocal=operator_at(frequency)
        opLocal=ni2019_isolated_groove_cluster_operator_complex( ...
            widths,depths,gaps,K,2*pi*frequency/cWater, ...
            'SMax',opt.SMax,'PanelsPerPi',opt.PanelsPerPi);
    end
    function residual=projected_equation(x)
        opLocal=operator_at((x(1)+1i*x(2))*1e3);
        value=u'*(opLocal.F./rowScale./columnScale)*v;
        residual=[real(value);imag(value)];
    end
end
