function cases = ni2019_case_library(varargin)
%NI2019_CASE_LIBRARY Every distinct geometry printed in Ni et al. (2019).
%   CASES = NI2019_CASE_LIBRARY() uses lambda=1, N=101, K=10.
%   CASES = NI2019_CASE_LIBRARY('lambda',value,'N',value,'K',value)
%   overrides those defaults. All printed geometric parameters are stored
%   verbatim; no fitting or correction is silently applied.

p = inputParser;
addParameter(p,'lambda',1,@(x)isnumeric(x)&&isscalar(x)&&x>0);
addParameter(p,'N',101,@(x)isnumeric(x)&&isscalar(x)&&mod(x,2)==1);
addParameter(p,'K',10,@(x)isnumeric(x)&&isscalar(x)&&x>=1);
parse(p,varargin{:});

b.lambda = p.Results.lambda;
b.theta_i_deg = 0;
b.N = p.Results.N;
b.K = p.Results.K;

cases = repmat(struct( ...
    'id','', 'figure','', 'name','', 'cfg',struct(), ...
    'target_orders',[], 'paper_angles_deg',[], ...
    'paper_amplitudes',[], 'paper_efficiencies',[], 'note',''),1,6);

cases(1) = make_case('F2a','Fig. 2(a), Fig. 3','-81 deg reflector', ...
    1/sind(81),[.500 .148],[.399 .121],.111,-1,-81,[],[], ...
    'Paper states almost complete conversion; no exact FFT amplitude is printed.');

cases(2) = make_case('F2b','Fig. 2(b)','-88 deg reflector', ...
    1/sind(88),[.085 .527],[.419 .070],.101,-1,-88,[],[], ...
    'Paper states almost 100 percent conversion; no exact FFT amplitude is printed.');

cases(3) = make_case('F2c','Fig. 2(c), Fig. 4(c)','symmetric splitter, paper sqrt(5):3 label', ...
    1/sind(72),[.159 .230],[.229 .170],.176,[-1 1],[-72 72], ...
    [1.5431 .9216],[], ...
    'Printed FEM pressure-amplitude ratio is approximately 5:3.');

cases(4) = make_case('F2d','Fig. 2(d), Fig. 4(b)','symmetric 1:1 splitter', ...
    1/sind(72),[.094 .229],[.207 .205],.206,[-1 1],[-72 72], ...
    [1.2729 1.2719],[], ...
    'Printed FEM pressure amplitudes are 1.2729 and 1.2719.');

cases(5) = make_case('F4a','Fig. 4(a)','symmetric 0:1 splitter (as printed)', ...
    1/sind(72),[.182 .480],[.182 .480],.071,1,72,[],1, ...
    ['Direct calculation of the printed parameters does not meet the 0:1 target. ' ...
     'This case is intentionally not silently corrected.']);

cases(6) = make_case('F5','Fig. 5, Fig. 6','four-groove unequal-angle splitter', ...
    2/sind(81),[.101 .107 .101 .104],[.186 .321 .126 .254], ...
    [.105 .101 .101],[-1 2],[-28.4 81],[.7562 1.7883],[.5030 .5003], ...
    ['The printed -28.4 deg angle is inconsistent with the printed period; ' ...
     'the grating equation gives -29.594 deg.']);

    function s = make_case(id,fig,name,aOverLambda,wfrac,dfrac,gfrac, ...
            orders,angles,amps,effs,note)
        cfg = b;
        cfg.a = aOverLambda*b.lambda;
        cfg.widths = wfrac*cfg.a;
        cfg.depths = dfrac*b.lambda;
        cfg.gaps = gfrac*cfg.a;
        s = struct('id',id,'figure',fig,'name',name,'cfg',cfg, ...
            'target_orders',orders,'paper_angles_deg',angles, ...
            'paper_amplitudes',amps,'paper_efficiencies',effs,'note',note);
    end
end
