%% Scale-transport of the verified strict root from 200 kHz to 180 kHz
clear; close all; clc;
rootDir=fileparts(mfilename('fullpath')); outputDir=fullfile(rootDir,'results');
addpath(rootDir);
D=load(fullfile(outputDir,'StrictRayleighBIC_200kHz_min1mm.mat'));
x=D.xFinal(:).'; cWater=1500; fTarget=180e3;
kappa=x(1); Omega=1-kappa; thetaDeg=asind(kappa/Omega);
aPhysical=cWater*Omega/fTarget; lambdaPhysical=cWater/fTarget;
depthsMm=1e3*aPhysical*x(2:3); widthsMm=1e3*aPhysical*x(4:5);
gapMm=1e3*aPhysical*x(6);

cfg=struct('a',1,'lambda',1/Omega,'theta_i_deg',thetaDeg, ...
    'depths',x(2:3),'widths',x(4:5),'gaps',x(6), ...
    'N',313,'K',39,'solve_scattering',false);
strict=ni2019_strict_rayleigh_operator(cfg,'TargetOrder',-1, ...
    'KyTolerance',1e-6);
op=ni2019_full_eigen_operator_complex(cfg,2*pi*Omega,2*pi*kappa,-1,0);
[~,S,V]=svd(op.Fscaled,'econ'); sv=diag(S);
z=V(:,end)./transpose(op.column_scale);
fullSigma=sv(end)/max(sv(1),eps);
fullRaw=norm(op.F*z)/max(norm(z),eps);

accepted=widthsMm(2)>=.8-1e-9 && gapMm>=1-1e-9 && ...
    strict.sigma_ratio<1e-10 && fullSigma<1e-10;
summary=table(fTarget/1e3,cWater,lambdaPhysical*1e3,aPhysical*1e3, ...
    kappa,Omega,thetaDeg,depthsMm(1),depthsMm(2),widthsMm(1), ...
    widthsMm(2),gapMm,strict.sigma_ratio,strict.strict_residual, ...
    fullSigma,fullRaw,accepted, ...
    'VariableNames',{'frequency_kHz','sound_speed_mps','lambda_mm', ...
    'period_mm','kappa','Omega','theta_deg','d1_mm','d2_mm', ...
    'w1_mm','w2_mm','gap_mm','strict_sigma','strict_raw', ...
    'full_sigma','full_raw','meets_w2_0p8_gap_1mm'});
writetable(summary,fullfile(outputDir, ...
    'StrictRayleighBIC_180kHz_w2min0p8_gapmin1mm.csv'));
save(fullfile(outputDir,'StrictRayleighBIC_180kHz_w2min0p8_gapmin1mm.mat'), ...
    'D','x','fTarget','cWater','kappa','Omega','thetaDeg', ...
    'aPhysical','lambdaPhysical','depthsMm','widthsMm','gapMm', ...
    'cfg','strict','op','fullSigma','fullRaw','accepted','summary');
disp(summary);
