%% Three-groove Gamma double-Rayleigh search with 1 mm lateral features
% Water: c=1500 m/s, f=200 kHz, hence a=lambda=7.5 mm.  Every groove
% width and every edge-to-edge gap, including the gap across the periodic
% boundary, is constrained to be at least 1 mm.
clear; close all; clc;

outputDir=fullfile(fileparts(mfilename('fullpath')),'results');
if ~exist(outputDir,'dir'), mkdir(outputDir); end

cWater=1500; frequency=200e3;
aMm=1e3*cWater/frequency;
minimumFeatureMm=1;
h=minimumFeatureMm/aMm;
fillMax=1-h; % leaves at least h across the periodic boundary

% Converged unconstrained odd root, retained as the reference.
xOriginal=[0.192681441082727 0.676102882473460 0.192681441082525 ...
    0.0917192490036675 0.529780736125398 0.0917192490043602 ...
    0.0736588091900755 0.0736588091898476];

% Best finite-feature parity candidates from constrained global/multistart
% searches. y=[d_outer,d_center,w_outer,w_center,g_internal]/a.
yOdd=[0.5011781881 0.3351271475 h h 0.2268799294];
yEven=[1.089612956 0.5601109888 h h h];
xOdd=expand_symmetric(yOdd);
xEven=expand_symmetric(yEven);
% A 0.01-mm numerical clearance converts the closed >=1 mm search bound
% into a literal >1 mm probe without changing the optimized depths/gaps.
hStrict=1.01/aMm;
fillMaxStrict=1-hStrict;
yOddStrict=[yOdd(1:2) hStrict hStrict yOdd(5)];
xOddStrict=expand_symmetric(yOddStrict);
% Independent multistart searches with the literal 1.01-mm lower bound and
% depths extended through 3a.  Both points are retained even though the
% high-order cross-check below rejects them.
yOddStrictOptimized=[0.509770395487 1.093265766833 hStrict hStrict ...
    0.203449943467];
yEvenStrictOptimized=[1.495845951865 0.500076549694 hStrict ...
    0.237524404039 0.179237797981];
xOddStrictOptimized=expand_symmetric(yOddStrictOptimized);
xEvenStrictOptimized=expand_symmetric(yEvenStrictOptimized);

runGlobalSearch=strcmp(getenv('NI2019_MIN1MM_GLOBAL_SEARCH'),'1');
if runGlobalSearch
    searchCfg=make_cfg(xOddStrict,41,5);
    globalResult=ni2019_optimize_three_groove_double_rayleigh_bic( ...
        searchCfg,'Truncations',[31 3;41 5;57 7], ...
        'Parameterization','both','DepthRange',[.03 3.00], ...
        'WidthRange',[hStrict .50],'GapRange',[hStrict .40], ...
        'FillMax',fillMaxStrict,'Starts',12,'UseGlobal',true, ...
        'GlobalSwarmSize',96,'GlobalMaxIterations',80, ...
        'GlobalMaxStallIterations',22, ...
        'MaxFunctionEvaluations',2400,'MaxIterations',350, ...
        'BoundaryPenaltyWeight',0,'RandomSeed',20260823,'Display','off');
else
    globalResult=[];
end

Klist=[3 5 7 9 11 15 19 23 31 39].';
Nlist=[41 41 57 73 89 121 153 185 249 313].';
original=evaluate_sequence(xOriginal,'odd',Nlist,Klist);
odd=evaluate_sequence(xOdd,'odd',Nlist,Klist);
even=evaluate_sequence(xEven,'even',Nlist,Klist);
oddStrict=evaluate_sequence(xOddStrict,'odd',Nlist,Klist);
oddStrictOptimized=evaluate_sequence( ...
    xOddStrictOptimized,'odd',Nlist,Klist);
evenStrictOptimized=evaluate_sequence( ...
    xEvenStrictOptimized,'even',Nlist,Klist);

% Manufacturing checks. boundaryGap is the full edge-to-edge distance from
% groove 3 to groove 1 of the adjacent period, not a half-cell margin.
parameterTable=make_parameter_table( ...
    {'unconstrained_root','min1mm_odd_candidate', ...
    'min1mm_even_candidate','gt1p01mm_odd_probe', ...
    'gt1p01mm_odd_depth3a','gt1p01mm_even_depth3a'}, ...
    [xOriginal;xOdd;xEven;xOddStrict;xOddStrictOptimized; ...
    xEvenStrictOptimized],aMm,minimumFeatureMm);

% The largest possible center width follows by placing the other two widths
% and all three periodic gaps at their minimum.
centerWidthMaxMm=aMm-5*minimumFeatureMm;
centerCutoffMm=aMm/2;
centerBetaSqMax=(2*pi)^2-(pi/(centerWidthMaxMm/aMm))^2;
centerGammaMin=sqrt(-centerBetaSqMax);

% q-wise aperture composition at a representative high truncation.
compositionId=find(Klist==15,1);
composition=table((0:5).', ...
    original.pressure_q_fraction(1:6,compositionId), ...
    oddStrictOptimized.pressure_q_fraction(1:6,compositionId), ...
    evenStrictOptimized.pressure_q_fraction(1:6,compositionId), ...
    original.velocity_q_fraction(1:6,compositionId), ...
    oddStrictOptimized.velocity_q_fraction(1:6,compositionId), ...
    evenStrictOptimized.velocity_q_fraction(1:6,compositionId), ...
    'VariableNames',{'q','p_original','p_odd_gt1mm','p_even_gt1mm', ...
    'v_original','v_odd_gt1mm','v_even_gt1mm'});

records=[sequence_table('unconstrained_root','odd',original); ...
    sequence_table('min1mm_odd_candidate','odd',odd); ...
    sequence_table('min1mm_even_candidate','even',even); ...
    sequence_table('gt1p01mm_odd_probe','odd',oddStrict); ...
    sequence_table('gt1p01mm_odd_depth3a','odd', ...
    oddStrictOptimized); ...
    sequence_table('gt1p01mm_even_depth3a','even', ...
    evenStrictOptimized)];

% ------------------------------- Figure -------------------------------
colors=ni2019_viridis(9);
purple=colors(2,:); blue=colors(4,:); green=colors(6,:);
yellow=colors(9,:); red=[.88 .12 .10]; gray=[.55 .55 .57];
fig=figure('Color','w','Position',[35 35 1510 870]);
tiledlayout(2,3,'TileSpacing','compact','Padding','compact');

nexttile;
draw_geometry(xOriginal,0,purple,.45);
draw_geometry(xOddStrictOptimized,-1.35,green,.65);
xlim([0 1]); ylim([-2.70 .12]); axis equal;
xlabel('x/a'); ylabel('shifted y/a');
title('(a) Original and >1-mm-constrained cells');
text(.5,-.92,'original','HorizontalAlignment','center');
text(.5,-2.58,'1.01 mm minimum','HorizontalAlignment','center');
style_axes(gca);

nexttile;
wMm=linspace(.75,4.5,400);
betaSq=(2*pi)^2-(pi./(wMm/aMm)).^2;
plot(wMm,betaSq,'Color',purple,'LineWidth',1.7); hold on;
yline(0,'--','Color',gray);
xline(centerWidthMaxMm,':','Color',red,'LineWidth',1.3);
xline(centerCutoffMm,'-.','Color',blue,'LineWidth',1.3);
plot(xOriginal(5)*aMm,(2*pi)^2-(pi/xOriginal(5))^2,'o', ...
    'Color',yellow,'MarkerFaceColor',yellow,'MarkerSize',6);
grid on; xlabel('center-groove width (mm)'); ylabel('\beta_1^2 a^2');
title('(b) Manufacturing bound closes q=1');
legend('q=1 dispersion','\beta_1^2=0','maximum with 1-mm features', ...
    'q=1 cutoff','original center width','Location','southeast');
style_axes(gca);

nexttile;
semilogy(Klist,original.sigma_ratio,'-o','Color',purple, ...
    'MarkerFaceColor',purple,'LineWidth',1.5); hold on;
semilogy(Klist,oddStrictOptimized.sigma_ratio,'-s','Color',green, ...
    'MarkerFaceColor',green,'LineWidth',1.5);
semilogy(Klist,evenStrictOptimized.sigma_ratio,'-^','Color',red, ...
    'MarkerFaceColor',red,'LineWidth',1.4);
yline(1e-8,':','Color',gray);
grid on; xlabel('transverse truncation K');
ylabel('\sigma_{min}/\sigma_{max}'); title('(c) Strict compatibility');
legend('unconstrained odd root','1.01-mm-minimum odd candidate', ...
    '1.01-mm-minimum even candidate','10^{-8} guide', ...
    'Location','southwest');
style_axes(gca);

nexttile;
semilogy(Klist,original.full_raw_residual,'-o','Color',purple, ...
    'MarkerFaceColor',purple,'LineWidth',1.5); hold on;
semilogy(Klist,oddStrictOptimized.full_raw_residual,'-s','Color',green, ...
    'MarkerFaceColor',green,'LineWidth',1.5);
semilogy(Klist,evenStrictOptimized.full_raw_residual,'-^','Color',red, ...
    'MarkerFaceColor',red,'LineWidth',1.4);
yline(1e-8,':','Color',gray);
grid on; xlabel('transverse truncation K');
ylabel('||Fz||_2/||z||_2'); title('(d) Complete homogeneous residual');
legend('unconstrained odd root','1.01-mm-minimum odd candidate', ...
    '1.01-mm-minimum even candidate','10^{-8} guide', ...
    'Location','southwest');
style_axes(gca);

nexttile;
plot(Klist,original.physical_groove_fraction,'-o','Color',purple, ...
    'MarkerFaceColor',purple,'LineWidth',1.5); hold on;
plot(Klist,oddStrictOptimized.physical_groove_fraction,'-s','Color',green, ...
    'MarkerFaceColor',green,'LineWidth',1.5);
plot(Klist,evenStrictOptimized.physical_groove_fraction,'-^','Color',red, ...
    'MarkerFaceColor',red,'LineWidth',1.4);
grid on; ylim([0 1.05]); xlabel('transverse truncation K');
ylabel('physical groove fraction'); title('(e) Mode localization');
legend('unconstrained odd root','1.01-mm-minimum odd candidate', ...
    '1.01-mm-minimum even candidate','Location','best');
style_axes(gca);

nexttile;
b=bar(composition.q,[composition.p_original, ...
    composition.p_odd_gt1mm,composition.p_even_gt1mm],.84);
b(1).FaceColor=purple; b(2).FaceColor=green; b(3).FaceColor=red;
grid on; xlabel('transverse order q');
ylabel('surface-pressure fraction');
title('(f) Aperture composition at K=15');
legend('unconstrained odd root','1.01-mm-minimum odd candidate', ...
    '1.01-mm-minimum even candidate','Location','northoutside');
style_axes(gca);

allLegend=findobj(fig,'Type','Legend');
set(allLegend,'Color','w','TextColor',[.10 .10 .12], ...
    'EdgeColor',[.55 .55 .58]);

figureFile=fullfile(outputDir, ...
    'ThreeGrooveDoubleRayleighBIC_min1mm.png');
exportgraphics(fig,figureFile,'Resolution',220);
dataFile=fullfile(outputDir, ...
    'ThreeGrooveDoubleRayleighBIC_min1mm.mat');
tableFile=fullfile(outputDir, ...
    'ThreeGrooveDoubleRayleighBIC_min1mm_convergence.csv');
parameterFile=fullfile(outputDir, ...
    'ThreeGrooveDoubleRayleighBIC_min1mm_parameters.csv');
writetable(records,tableFile);
writetable(parameterTable,parameterFile);
save(dataFile,'aMm','frequency','minimumFeatureMm','h','hStrict','fillMax', ...
    'fillMaxStrict', ...
    'xOriginal','xOdd','xEven','xOddStrict','xOddStrictOptimized', ...
    'xEvenStrictOptimized','original','odd','even','oddStrict', ...
    'oddStrictOptimized','evenStrictOptimized', ...
    'parameterTable','records','composition','centerWidthMaxMm', ...
    'centerCutoffMm','centerBetaSqMax','centerGammaMin','globalResult');

fprintf('\nThree-groove 1-mm manufacturing-constrained search\n');
fprintf('  a = %.6f mm, normalized minimum h = %.12g\n',aMm,h);
fprintf('  maximum center width = %.6f mm; q1 cutoff = %.6f mm\n', ...
    centerWidthMaxMm,centerCutoffMm);
fprintf('  beta1^2*a^2 <= %.9f, gamma1*a >= %.9f\n', ...
    centerBetaSqMax,centerGammaMin);
fprintf('  best odd finite-feature candidate [mm]:\n');
fprintf('    depths = [%.6f %.6f %.6f]\n',xOdd(1:3)*aMm);
fprintf('    widths = [%.6f %.6f %.6f]\n',xOdd(4:6)*aMm);
fprintf('    gaps internal = [%.6f %.6f], boundary = %.6f\n', ...
    xOdd(7:8)*aMm,(1-sum(xOdd(4:8)))*aMm);
fprintf('  K=39 odd: sigma %.3e, full raw %.3e, groove %.4f\n', ...
    odd.sigma_ratio(end),odd.full_raw_residual(end), ...
    odd.physical_groove_fraction(end));
fprintf('  K=39 even: sigma %.3e, full raw %.3e, groove %.4f\n', ...
    even.sigma_ratio(end),even.full_raw_residual(end), ...
    even.physical_groove_fraction(end));
fprintf(['  literal >1 mm probe (width 1.01 mm): sigma %.3e, ', ...
    'full raw %.3e, boundary gap %.6f mm\n'], ...
    oddStrict.sigma_ratio(end),oddStrict.full_raw_residual(end), ...
    (1-sum(xOddStrict(4:8)))*aMm);
fprintf(['  depth<=3a >1 mm odd: sigma %.3e, full raw %.3e, ', ...
    'minimum feature %.6f mm\n'], ...
    oddStrictOptimized.sigma_ratio(end), ...
    oddStrictOptimized.full_raw_residual(end), ...
    min([xOddStrictOptimized(4:8), ...
    1-sum(xOddStrictOptimized(4:8))])*aMm);
fprintf(['  depth<=3a >1 mm even: sigma %.3e, full raw %.3e, ', ...
    'minimum feature %.6f mm\n'], ...
    evenStrictOptimized.sigma_ratio(end), ...
    evenStrictOptimized.full_raw_residual(end), ...
    min([xEvenStrictOptimized(4:8), ...
    1-sum(xEvenStrictOptimized(4:8))])*aMm);
fprintf(['  verdict: no strict Gamma double-Rayleigh BIC was found ', ...
    'under the 1-mm lateral constraint.\n']);
fprintf('  figure: %s\n  data:   %s\n  table:  %s\n', ...
    figureFile,dataFile,parameterFile);

assignin('base','ThreeGrooveMin1mm',struct('parameters',parameterTable, ...
    'convergence',records,'original',original,'odd',odd,'even',even, ...
    'oddStrict',oddStrict,'oddStrictOptimized',oddStrictOptimized, ...
    'evenStrictOptimized',evenStrictOptimized, ...
    'figure',figureFile,'data',dataFile));

function x=expand_symmetric(y)
x=[y(1) y(2) y(1) y(3) y(4) y(3) y(5) y(5)];
end

function cfg=make_cfg(x,N,K)
cfg=struct('a',1,'lambda',1,'theta_i_deg',0, ...
    'depths',x(1:3),'widths',x(4:6),'gaps',x(7:8), ...
    'N',N,'K',K,'solve_scattering',false);
end

function out=evaluate_sequence(x,parity,Nlist,Klist)
n=numel(Klist);
out=struct('N',Nlist,'K',Klist,'sigma_ratio',zeros(n,1), ...
    'full_raw_residual',zeros(n,1), ...
    'physical_groove_fraction',zeros(n,1), ...
    'pressure_q_fraction',nan(max(Klist),n), ...
    'velocity_q_fraction',nan(max(Klist),n),'parity',parity,'x',x);
for j=1:n
    R=ni2019_three_groove_parity_strict_operator( ...
        make_cfg(x,Nlist(j),Klist(j)),parity);
    out.sigma_ratio(j)=R.sigma_ratio;
    out.full_raw_residual(j)=R.strict_residual;
    out.physical_groove_fraction(j)= ...
        R.diagnostics.physical_groove_fraction;
    out.pressure_q_fraction(1:Klist(j),j)= ...
        R.transverse.surface_pressure_fraction_by_q;
    out.velocity_q_fraction(1:Klist(j),j)= ...
        R.transverse.surface_velocity_fraction_by_q;
end
end

function T=sequence_table(name,parity,r)
T=table(repmat(string(name),numel(r.K),1), ...
    repmat(string(parity),numel(r.K),1),r.N,r.K,r.sigma_ratio, ...
    r.full_raw_residual,r.physical_groove_fraction, ...
    'VariableNames',{'candidate','parity','N','K','sigma_ratio', ...
    'full_raw_residual','physical_groove_fraction'});
end

function T=make_parameter_table(names,X,aMm,minFeatureMm)
n=size(X,1); boundaryGap=1-sum(X(:,4:8),2);
T=table(string(names(:)),repmat(aMm,n,1), ...
    X(:,1)*aMm,X(:,2)*aMm,X(:,3)*aMm, ...
    X(:,4)*aMm,X(:,5)*aMm,X(:,6)*aMm, ...
    X(:,7)*aMm,X(:,8)*aMm,boundaryGap*aMm, ...
    'VariableNames',{'candidate','period_mm','d1_mm','d2_mm','d3_mm', ...
    'w1_mm','w2_mm','w3_mm','g1_mm','g2_mm','boundary_gap_mm'});
featureMatrix=[T.w1_mm,T.w2_mm,T.w3_mm,T.g1_mm,T.g2_mm, ...
    T.boundary_gap_mm];
T.minimum_lateral_feature_mm=min(featureMatrix,[],2);
T.meets_closed_1mm_constraint=T.minimum_lateral_feature_mm>= ...
    minFeatureMm-1e-9;
T.meets_strict_gt1mm_constraint=T.minimum_lateral_feature_mm> ...
    minFeatureMm+1e-9;
end

function draw_geometry(x,yShift,color,alphaValue)
occupied=sum(x(4:8)); x0=.5*(1-occupied);
xl=[x0,x0+x(4)+x(7),x0+x(4)+x(7)+x(5)+x(8)];
for ell=1:3
    patch([xl(ell) xl(ell)+x(3+ell) xl(ell)+x(3+ell) xl(ell)], ...
        yShift+[0 0 -x(ell) -x(ell)],color,'FaceAlpha',alphaValue, ...
        'EdgeColor',color,'LineWidth',1.0); hold on;
end
plot([0 1],[yShift yShift],'-','Color',[.12 .12 .14],'LineWidth',1.4);
end

function style_axes(ax)
ax.FontName='Helvetica'; ax.FontSize=10; ax.LineWidth=.8;
ax.TickDir='out'; ax.Color='w'; ax.XColor=[.10 .10 .12];
ax.YColor=[.10 .10 .12]; ax.GridColor=[.68 .68 .70];
ax.MinorGridColor=[.82 .82 .84]; ax.Title.Color=[.10 .10 .12];
box(ax,'on');
end
