function result = test_radiation_zero_diagnostic()
%TEST_RADIATION_ZERO_DIAGNOSTIC Reproduce the numerator/denominator check.
%
% This is intentionally a focused validation command for the candidate in
% run_Ni2019_single_rayleigh_bic_validation.m.  It does not write figures or
% MAT files.  Run from Ni2019_MATLAB with:
%
%   result = test_radiation_zero_diagnostic;

a = 1;
kappa0 = 0.240035321859;
Omega0 = 1-kappa0;
cfg = struct('a',a,'lambda',a/Omega0, ...
    'theta_i_deg',asind(kappa0/Omega0), ...
    'depths',[0.682459207769 0.122072875277], ...
    'widths',[0.658186442030 0.052212626051], ...
    'gaps',0.144800546474,'N',101,'K',14, ...
    'solve_scattering',false);

result = ni2019_radiation_zero_diagnostic(cfg, ...
    'Kappa',kappa0,'Omega',Omega0,'TargetOrder',-1, ...
    'NList',[41 61 81 101], ...
    'KList',[6 8 10 12 14 16], ...
    'GridN',101,'GridK',14, ...
    'KappaOffsets',[-.02 -.01 -.005 0 .005 .01 .02], ...
    'OmegaOffsets',[-.02 -.01 0 .01 .02], ...
    'Verbose',true);

fprintf('\nCenter diagnostics at N=%d, K=%d\n', ...
    result.center.N,result.center.K);
fprintf('  pole denominator                 %.12e\n', ...
    result.center.pole_denominator);
fprintf('  finite-channel numerator residual %.12e\n', ...
    result.center.finite_channel_numerator_residual);
fprintf('  target raw coupling [excluded]    %.12e\n', ...
    result.center.target_raw_coupling);
fprintf('  groove-mode fraction              %.12e\n', ...
    result.center.groove_fraction);
fprintf('  open non-target orders             ');
fprintf('%d ',result.center.open_non_target_orders);
fprintf('\n');

fprintf('\nN convergence [N, denominator, numerator]\n');
for ii = 1:numel(result.center_by_N)
    ev = result.center_by_N{ii};
    fprintf('  %3d %.12e %.12e\n',ev.N,ev.pole_denominator, ...
        ev.finite_channel_numerator_residual);
end
fprintf('\nK convergence [K, denominator, numerator]\n');
for ii = 1:numel(result.center_by_K)
    ev = result.center_by_K{ii};
    fprintf('  %3d %.12e %.12e\n',ev.K,ev.pole_denominator, ...
        ev.finite_channel_numerator_residual);
end

fprintf('\nLocal minima\n');
fprintf('  pole       %.12e at [kappa Omega]=[%.9f %.9f]\n', ...
    result.pole_minimum.value,result.pole_minimum.coordinate);
fprintf('  radiation  %.12e at [kappa Omega]=[%.9f %.9f]\n', ...
    result.radiation_minimum.value,result.radiation_minimum.coordinate);
fprintf('  separation %.12e; one-grid-cell=%d\n', ...
    result.minima_distance,result.minima_within_one_grid_cell);
fprintf('\n%s\n',result.verdict);
end
