function T=test_two_groove_odd_strict_operator()
%TEST_TWO_GROOVE_ODD_STRICT_OPERATOR Verify the exact odd-sector map.

root=fileparts(mfilename('fullpath'));
if isempty(strfind(path,root)) %#ok<STREMP>
    addpath(root);
end

cfg=struct('a',1,'lambda',1,'theta_i_deg',0, ...
    'depths',[.42 .42],'widths',[.19 .19],'gaps',.27, ...
    'N',41,'K',7,'solve_scattering',false);
R=ni2019_two_groove_odd_strict_operator(cfg);

P=(cfg.N-1)/2;
assert(isequal(R.removed_orders(:),[-1;0;1]), ...
    'The Gamma non-decaying orders were not removed.');
assert(isequal(size(R.F_odd_raw),[cfg.K+P,cfg.K+P-1]), ...
    'The independent odd strict system must be one-row tall.');
assert(all(R.radiation.removed_amplitudes==0) && ...
    R.radiation.total_propagating_power==0, ...
    'The strict odd basis retained a non-decaying amplitude.');
assert(R.parity.odd_coefficient_residual<1e-13 && ...
    R.parity.even_coefficient_residual>1, ...
    'The reconstructed groove coefficients violate odd parity.');

A=R.mode.A;
for n=2:P
    assert(abs(A(R.full_operator.orders==-n)+ ...
        A(R.full_operator.orders==n))<1e-13, ...
        'The exterior odd-parity relation failed at n=%d.',n);
end
assert(abs(norm(R.mode.z_full)-1)<1e-13, ...
    'The reconstructed full mode is not normalized.');
assert(abs(norm(R.full_operator.F*R.mode.z_full)-R.strict_residual)<1e-12, ...
    'The reported raw residual is inconsistent with the full operator.');
assert(numel(R.transverse.q)==cfg.K && ...
    abs(sum(R.transverse.surface_pressure_fraction_by_q)-1)<1e-12 && ...
    abs(sum(R.transverse.surface_velocity_fraction_by_q)-1)<1e-12, ...
    'The transverse-mode fractions are invalid.');

% K=1 is retained as an ablation: it has no transverse correction and is
% expected to remain far from a strict double-Rayleigh compatibility zero.
cfg.K=1;
R1=ni2019_two_groove_odd_strict_operator(cfg);
assert(R1.transverse.surface_pressure_higher_order_fraction==0 && ...
    R1.transverse.surface_velocity_higher_order_fraction==0, ...
    'The K=1 ablation unexpectedly contains a higher transverse mode.');

fprintf('two-groove odd strict operator test passed.\n');
fprintf('  K=7 sigma ratio %.6e, raw residual %.6e\n', ...
    R.sigma_ratio,R.strict_residual);
fprintf('  K=1 sigma ratio %.6e, raw residual %.6e\n', ...
    R1.sigma_ratio,R1.strict_residual);

T=struct('high_order',R,'fundamental_only',R1);
end
