function T = test_two_groove_even_strict_operator()
%TEST_TWO_GROOVE_EVEN_STRICT_OPERATOR Validate the even Gamma sector.
%   Run from Ni2019_MATLAB with:
%       test_two_groove_even_strict_operator;

root = fileparts(mfilename('fullpath'));
if isempty(strfind(path,root)) %#ok<STREMP>
    addpath(root);
end

cfg = struct('a',1,'lambda',1,'theta_i_deg',0, ...
    'depths',[0.28 0.28],'widths',[0.18 0.18],'gaps',0.32, ...
    'N',41,'K',5,'solve_scattering',false);
R = ni2019_two_groove_even_strict_operator(cfg,'Verbose',false);

assert(isequal(R.removed_orders(:),[-1;0;1]), ...
    'The even operator did not identify the three Gamma strict channels.');
assert(R.radiation.removed_amplitudes_exact_zero && ...
    all(R.radiation.removed_amplitudes==0), ...
    'Removed A_-1, A0, A+1 amplitudes are not exactly zero.');
assert(isequal(R.dimensions.even,[26 24]) && ...
    R.dimensions.extra_rows==2 && ...
    R.codimension.independent_strict_constraints==2, ...
    'The even sector is not two rows taller than its unknown vector.');
assert(all(isfinite(R.F_even_full_raw(:))) && ...
    all(isfinite(R.F_even_raw(:))) && all(isfinite(R.F_even_scaled(:))), ...
    'The even matrices contain NaN/Inf values.');
assert(strcmp(R.parity.label,'even') && ...
    R.parity.even_coefficient_residual<1e-12 && ...
    R.parity.odd_coefficient_residual>1, ...
    'The reconstructed mode does not satisfy mirror-even parity.');
assert(numel(R.transverse.q)==cfg.K && ...
    abs(sum(R.transverse.surface_pressure_fraction_by_q)-1)<1e-12 && ...
    abs(sum(R.transverse.surface_velocity_fraction_by_q)-1)<1e-12 && ...
    all(isfinite(R.transverse.surface_pressure_fraction_by_q)) && ...
    all(isfinite(R.transverse.surface_velocity_fraction_by_q)), ...
    'The q-wise pressure/velocity fractions are invalid.');
assert(isfinite(R.sigma_ratio) && isfinite(R.strict_residual) && ...
    isfinite(R.residual.scaled) && isfinite(R.residual.raw), ...
    'The even singular/raw residuals are not finite.');

fprintf('two-groove even strict operator test passed.\n');
fprintf('  even matrix: %d x %d (extra rows %d)\n', ...
    R.dimensions.even(1),R.dimensions.even(2),R.dimensions.extra_rows);
fprintf('  removed orders: %s\n',strtrim(sprintf('%d ',R.removed_orders)));
fprintf('  sigma ratio=%.6e, strict raw residual=%.6e\n', ...
    R.sigma_ratio,R.strict_residual);
fprintf('  q pressure fractions: ');
fprintf('%.6e ',R.transverse.surface_pressure_fraction_by_q);
fprintf('\n  q velocity fractions: ');
fprintf('%.6e ',R.transverse.surface_velocity_fraction_by_q);
fprintf('\n');

T = R;
end
