function T=test_track_leaky_pole_to_rayleigh
%TEST_TRACK_LEAKY_POLE_TO_RAYLEIGH Regression check for the independent
% leaky-pole continuation used in the single-Rayleigh candidate.

cfg=struct('a',1,'lambda',1/0.759964678141,'theta_i_deg',0, ...
    'depths',[0.682459207769 0.122072875277], ...
    'widths',[0.658186442030 0.052212626051], ...
    'gaps',0.144800546474,'N',101,'K',14,'solve_scattering',false);
T=ni2019_track_leaky_pole_to_rayleigh(cfg,0.240035321859, ...
    'NumSteps',21,'Verbose',false);

assert(abs(T.independent_start.q)>1e-3, ...
    'The independent start must be a nonzero complex q pole.');
assert(T.independent_start.sigma_ratio<1e-8, ...
    'The independently located start pole did not converge.');
assert(T.same_branch && ~any(T.jump_detected), ...
    'The continuation detected a branch jump.');
assert(min(T.mode_overlap(2:end-1))>.80, ...
    'Consecutive right-mode overlap is too small.');
assert(max(T.sigma_ratio(1:end-1))<1e-7, ...
    'A continued point has a large singular residual.');
assert(T.radiation_fraction(1)>1e-7 && ...
    T.radiation_fraction(end-1)<1e-8, ...
    'The path does not show finite-channel leakage collapsing toward the endpoint.');
assert(abs(T.q(end-1))<1e-5, ...
    'The tracked q did not approach the Rayleigh branch point.');
assert(T.groove_content(1)>.5 && T.groove_content(end-1)>.5, ...
    'The pole does not retain a nonzero groove-component diagnostic.');
fprintf('track test passed: start q=%+.6e%+.6ei, final |q|=%.3e, ', ...
    real(T.independent_start.q),imag(T.independent_start.q),abs(T.q(end-1)));
fprintf('min overlap=%.6f, max path sigma ratio=%.3e\n', ...
    min(T.mode_overlap(2:end-1)),max(T.sigma_ratio(1:end-1)));
end
