function T = test_three_groove_double_rayleigh_operator()
%TEST_THREE_GROOVE_DOUBLE_RAYLEIGH_OPERATOR
%   Regression test for the strict operator at Gamma with simultaneous
%   n=-1 and n=+1 Rayleigh thresholds.  The target is n=-1; the n=0
%   finite-open order and the other threshold order are also removed.
%
%   Run from Ni2019_MATLAB with:
%       test_three_groove_double_rayleigh_operator;

root = fileparts(mfilename('fullpath'));
if isempty(strfind(path,root)) %#ok<STREMP>
    addpath(root);
end

% Three separated grooves in one period.  Omega=a/lambda=1 and theta=0
% place n=+/-1 at the first double-Rayleigh threshold while n=0 remains
% finite-flux open.  The geometry is deliberately generic and is not an
% optimizer output.
cfg = struct('a',1,'lambda',1,'theta_i_deg',0, ...
    'depths',[0.28 0.19 0.34], ...
    'widths',[0.18 0.20 0.16], ...
    'gaps',[0.08 0.09], ...
    'N',41,'K',5,'solve_scattering',false);

R = ni2019_strict_rayleigh_operator(cfg, ...
    'TargetOrder',-1,'EnforceAllFiniteOpen',true, ...
    'EnforceOtherThreshold',true,'Verbose',false);

% Exact channel classification and zero insertion.
assert(R.target_is_rayleigh, ...
    'The target order is not classified as a Rayleigh threshold.');
assert(isequal(R.removed_orders(:),[-1;0;1]), ...
    'The removed order list is not [-1 0 1].');
targetId = R.full_operator.orders==(-1);
finiteId = ismember(R.full_operator.orders,R.finite_open_orders);
otherThresholdId = ismember(R.full_operator.orders,1);
assert(all(R.mode.A(targetId)==0), ...
    'The n=-1 threshold amplitude is not exactly zero.');
assert(all(R.mode.A(finiteId)==0), ...
    'The n=0 finite-open amplitude is not exactly zero.');
assert(all(R.mode.A(otherThresholdId)==0), ...
    'The n=+1 threshold amplitude is not exactly zero.');
assert(R.diagnostics.removed_amplitude_is_exact_zero, ...
    'At least one removed channel is not exactly zero.');

% Removing three A columns from the square full system must produce a
% 3-column-tall reduced system, including all retained high evanescent modes.
assert(R.dimensions.is_tall && ...
    R.dimensions.equations-R.dimensions.unknowns==3 && ...
    R.dimensions.removed_channels==3, ...
    'Reduced dimensions are not tall by exactly three channels.');
assert(isequal(R.dimensions.full,[R.full_operator.N+R.full_operator.n_groove, ...
        R.full_operator.N+R.full_operator.n_groove]), ...
    'The full matrix dimensions are inconsistent.');
assert(all(isfinite(R.F_full_raw(:))) && all(isfinite(R.F_reduced_raw(:))) && ...
    all(isfinite(R.F_reduced_scaled(:))), ...
    'Full or reduced matrices contain NaN/Inf values.');

% Check the reduced scaling identity and the physical reconstructed residual.
assert(R.residual.scaling_consistency<1e-12, ...
    'Reduced row/column scaling identity failed.');
assert(isfinite(R.residual.reduced_raw) && ...
    abs(R.residual.full_raw-R.residual.reduced_raw)<1e-12, ...
    'Full and reduced residuals are inconsistent.');

% The singular-vector candidate must contain a nontrivial groove component;
% this guards against an accidental all-exterior zero vector.
assert(norm(R.mode.C_physical)>1e-8 && ...
    norm(R.mode.z_full)>1e-8 && R.groove.n_groove==3*cfg.K, ...
    'The reconstructed mode does not contain a nontrivial groove component.');
assert(isfinite(R.sigma_ratio) && isfinite(R.strict_residual), ...
    'Singular or strict residual diagnostics are not finite.');

fprintf('three-groove Gamma double-Rayleigh test passed.\n');
fprintf('  cfg: N=%d, K=%d, full=%d x %d, reduced=%d x %d\n', ...
    cfg.N,cfg.K,R.dimensions.full(1),R.dimensions.full(2), ...
    R.dimensions.reduced(1),R.dimensions.reduced(2));
fprintf('  removed orders: %s\n',strtrim(sprintf('%d ',R.removed_orders)));
fprintf('  sigma ratio=%.6e, strict residual=%.6e, scaling residual=%.6e\n', ...
    R.sigma_ratio,R.strict_residual,R.residual.scaling_consistency);
fprintf('  groove coefficient norm=%.6e, finite-open power=%.6e\n', ...
    norm(R.mode.C_physical),R.radiation.finite_open_power);

T = R;
end
