function T = test_strict_rayleigh_operator()
%TEST_STRICT_RAYLEIGH_OPERATOR Validate exact channel removal and scaling.
%   Run from Ni2019_MATLAB with:
%       T = test_strict_rayleigh_operator;

root = fileparts(mfilename('fullpath'));
if isempty(strfind(path,root)) %#ok<STREMP>
    addpath(root);
end

kappa0 = 0.240035321859;
Omega0 = 1-kappa0;
candidate = struct('a',1,'lambda',1/Omega0, ...
    'theta_i_deg',asind(kappa0/Omega0), ...
    'depths',[0.682459207769 0.122072875277], ...
    'widths',[0.658186442030 0.052212626051], ...
    'gaps',0.144800546474,'N',101,'K',8,'solve_scattering',false);

Kvals = [6 8 10 12 14 16];
candidateResults = cell(1,numel(Kvals));
strictResidual = zeros(size(Kvals));
for j = 1:numel(Kvals)
    cfg = candidate;
    cfg.K = Kvals(j);
    candidateResults{j} = ni2019_strict_rayleigh_operator(cfg, ...
        'TargetOrder',-1,'EnforceAllFiniteOpen',true,'Verbose',false);
    r = candidateResults{j};
    targetId = r.full_operator.orders==r.target_order;
    finiteId = ismember(r.full_operator.orders,r.finite_open_orders);
    assert(all(r.mode.A(targetId)==0), ...
        'The target Rayleigh pressure amplitude is not exactly zero.');
    assert(all(r.mode.A(finiteId)==0), ...
        'A finite-open pressure amplitude is not exactly zero.');
    assert(r.dimensions.is_tall && ...
        r.dimensions.equations-r.dimensions.unknowns == ...
        r.dimensions.removed_channels, ...
        'The reduced matrix is not tall by the number of removed channels.');
    assert(r.residual.scaling_consistency<1e-12, ...
        'Reduced row/column scaling does not reconstruct the raw residual.');
    assert(isfinite(r.residual.full_raw) && ...
        abs(r.residual.full_raw-r.residual.reduced_raw)<1e-12, ...
        'The reconstructed full residual is inconsistent with the reduced residual.');
    assert(r.diagnostics.removed_amplitude_is_exact_zero, ...
        'Removed amplitudes are not exactly zero after reconstruction.');
    strictResidual(j) = r.residual.reduced_raw;
end

% A separate generic two-groove geometry checks that order classification and
% exact zero insertion do not depend on the previously investigated design.
generic = struct('a',1,'lambda',1/0.8,'theta_i_deg',asind(0.2/0.8), ...
    'depths',[0.30 0.17],'widths',[0.25 0.20],'gaps',0.15, ...
    'N',31,'K',4,'solve_scattering',false);
g = ni2019_strict_rayleigh_operator(generic,'TargetOrder',-1, ...
    'EnforceAllFiniteOpen',true,'Verbose',false);
targetId = g.full_operator.orders==g.target_order;
finiteId = ismember(g.full_operator.orders,g.finite_open_orders);
assert(all(g.mode.A(targetId)==0) && all(g.mode.A(finiteId)==0), ...
    'Generic geometry did not enforce the requested zero channels.');
assert(g.dimensions.is_tall && ...
    g.dimensions.equations-g.dimensions.unknowns == g.dimensions.removed_channels, ...
    'Generic reduced dimensions are inconsistent.');
assert(g.residual.scaling_consistency<1e-12 && ...
    isfinite(g.residual.full_raw) && ...
    abs(g.residual.full_raw-g.residual.reduced_raw)<1e-12, ...
    'Generic scaling or full residual check failed.');

% Verify the optional mode: with finite-open enforcement disabled only the
% requested target column is removed, while exact target insertion remains.
gTargetOnly = ni2019_strict_rayleigh_operator(generic,'TargetOrder',-1, ...
    'EnforceAllFiniteOpen',false,'Verbose',false);
assert(gTargetOnly.dimensions.removed_channels==1, ...
    'Target-only mode did not remove exactly one channel.');
assert(gTargetOnly.mode.A(gTargetOnly.target_index)==0, ...
    'Target-only mode did not enforce the target zero.');

fprintf('strict operator test passed.\n');
fprintf('  candidate K    strict raw residual\n');
for j = 1:numel(Kvals)
    fprintf('      %2d          %.6e\n',Kvals(j),strictResidual(j));
end
fprintf('  candidate removed orders: %s\n', ...
    strtrim(sprintf('%d ',candidateResults{2}.removed_orders)));
fprintf('  generic size: %d x %d, removed channels: %d\n', ...
    g.dimensions.equations,g.dimensions.unknowns,g.dimensions.removed_channels);

T = struct('candidate',candidateResults,'Kvals',Kvals, ...
    'strict_residual',strictResidual,'generic',g,'target_only',gTargetOnly);
end
