function T=test_three_groove_parity_strict_operator()
%TEST_THREE_GROOVE_PARITY_STRICT_OPERATOR Verify odd/even reductions.

root=fileparts(mfilename('fullpath'));
if isempty(strfind(path,root)) %#ok<STREMP>
    addpath(root);
end
cfg=struct('a',1,'lambda',1,'theta_i_deg',0, ...
    'depths',[.24 .46 .24],'widths',[.14 .31 .14], ...
    'gaps',[.14 .14],'N',41,'K',5,'solve_scattering',false);

Rodd=ni2019_three_groove_parity_strict_operator(cfg,'odd');
Reven=ni2019_three_groove_parity_strict_operator(cfg,'even');
assert(isequal(Rodd.removed_orders(:),[-1;0;1]) && ...
    isequal(Reven.removed_orders(:),[-1;0;1]), ...
    'The Gamma non-decaying channels were not removed.');
assert(Rodd.dimensions.extra_rows==1 && Reven.dimensions.extra_rows==2, ...
    'Odd/even independent systems have incorrect codimension.');
assert(isequal(Rodd.central_allowed_q(:),[1;3]) && ...
    isequal(Reven.central_allowed_q(:),[0;2;4]), ...
    'The central-groove parity selection rule failed.');
assert(Rodd.radiation.removed_amplitudes_exact_zero && ...
    Reven.radiation.removed_amplitudes_exact_zero, ...
    'A strict parity basis retained a removed channel.');
assert(Rodd.diagnostics.parity_residual<1e-13 && ...
    Reven.diagnostics.parity_residual<1e-13, ...
    'The reconstructed groove modes violate mirror parity.');
assert(abs(norm(Rodd.full_operator.F*Rodd.mode.z_full)- ...
    Rodd.strict_residual)<1e-12 && ...
    abs(norm(Reven.full_operator.F*Reven.mode.z_full)- ...
    Reven.strict_residual)<1e-12, ...
    'The reported full raw residual is inconsistent.');
assert(abs(sum(Rodd.transverse.surface_pressure_fraction_by_q)-1)<1e-12 && ...
    abs(sum(Reven.transverse.surface_velocity_fraction_by_q)-1)<1e-12, ...
    'The transverse fractions are invalid.');

fprintf('three-groove parity strict operator test passed.\n');
fprintf('  odd  size %d x %d, sigma %.6e, raw %.6e\n', ...
    Rodd.dimensions.parity,Rodd.sigma_ratio,Rodd.strict_residual);
fprintf('  even size %d x %d, sigma %.6e, raw %.6e\n', ...
    Reven.dimensions.parity,Reven.sigma_ratio,Reven.strict_residual);
T=struct('odd',Rodd,'even',Reven);
end
