function T = test_two_groove_parity_diagnostic()
%TEST_TWO_GROOVE_PARITY_DIAGNOSTIC Validate the Gamma mirror-odd reduction.
%   Run from Ni2019_MATLAB with:
%       test_two_groove_parity_diagnostic;

root = fileparts(mfilename('fullpath'));
if isempty(strfind(path,root)) %#ok<STREMP>
    addpath(root);
end

% Two identical side grooves, centered in one period. At Omega=1 and
% Gamma, n=+/-1 are the double-Rayleigh thresholds and n=0 is open.
cfg = struct('a',1,'lambda',1,'theta_i_deg',0, ...
    'depths',[0.28 0.28],'widths',[0.18 0.18],'gaps',0.32, ...
    'N',41,'K',5,'solve_scattering',false);
R = ni2019_strict_rayleigh_operator(cfg,'TargetOrder',-1, ...
    'EnforceAllFiniteOpen',true,'EnforceOtherThreshold',true);
D = ni2019_two_groove_parity_diagnostic(R,'Verbose',false);

assert(D.is_symmetric && D.geometry_mirror_error<1e-12, ...
    'The symmetric test geometry was not recognized.');
assert(strcmp(D.parity_label,'odd'), ...
    'The returned strict mode was not identified as mirror odd.');
assert(D.coefficient_residuals.odd<1e-8 && ...
    D.coefficient_residuals.even>1, ...
    'The local-cosine mirror law did not identify odd parity.');
assert(D.channel_residuals.A0<1e-12 && ...
    D.channel_residuals.odd_Aplus_plus_Aminus<1e-12, ...
    'Odd-channel relations A0=0 and A+1=-A-1 failed.');
assert(abs(D.channel_combination_amplitudes.odd_independent_threshold_amplitude)==0, ...
    'The strict test mode did not insert exact zero threshold amplitudes.');
assert(numel(D.q_wise.coefficient_norm)==cfg.K && ...
    all(isfinite(D.q_wise.coefficient_energy_proxy)) && ...
    all(isfinite(D.q_wise.source_coupling_norm)), ...
    'The q-wise diagnostics are invalid.');
assert(D.q0_only.unit_odd_q0_coupling_norm>1e-6 && ...
    ~D.q0_only.nontrivial_q0_can_be_nonradiating, ...
    'The q=0-only non-cancellation diagnostic failed.');
assert(all(isfinite(D.groove_by_groove_norms)) && ...
    norm(D.groove_by_groove_norms)>1e-8, ...
    'The groove-by-groove mode diagnostic is trivial or nonfinite.');

% Asymmetry must suppress the parity label rather than produce a false one.
cfgAsym = cfg;
cfgAsym.depths(2) = cfgAsym.depths(2)+1e-3;
Rasym = ni2019_strict_rayleigh_operator(cfgAsym,'TargetOrder',-1, ...
    'EnforceAllFiniteOpen',true,'EnforceOtherThreshold',true);
Dasym = ni2019_two_groove_parity_diagnostic(Rasym);
assert(~Dasym.is_symmetric && isnan(Dasym.parity_sign) && ...
    contains(Dasym.parity_label,'asymmetric'), ...
    'Asymmetric geometry was assigned a false parity.');

fprintf('two-groove parity diagnostic test passed.\n');
fprintf('  mirror error=%.6e, label=%s\n', ...
    D.geometry_mirror_error,D.parity_label);
fprintf('  even/odd coefficient residuals=%.6e / %.6e\n', ...
    D.coefficient_residuals.even,D.coefficient_residuals.odd);
fprintf('  channel residuals even/odd/A0=%.6e / %.6e / %.6e\n', ...
    D.channel_residuals.even_Aplus_minus_Aminus, ...
    D.channel_residuals.odd_Aplus_plus_Aminus,D.channel_residuals.A0);
fprintf('  q-wise source norms: ');
fprintf('%.6e ',D.q_wise.source_coupling_norm);
fprintf('\n  q0 coupling=%.6e, strict |A_-1|=%.6e\n', ...
    D.q0_only.unit_odd_q0_coupling_norm, ...
    abs(D.channel_combination_amplitudes.odd_independent_threshold_amplitude));

T = struct('symmetric',D,'asymmetric',Dasym,'cfg',cfg);
end
